language: python
python:
- '2.7'
script: python tests/test_simplenote.py
branches:
  only:
  - master
deploy:
  provider: pypi
  user: mrtazz
  password:
    secure: YGE8ORgwhVQz7cdfqhrV28qDDn3svvSVO6bAbi5wDxOf5/y6cPPKPH4/sD1T9FkqEXsCzGJxUUoUTPYZ2jotSqqTWmVz+NZ98Mh/7bBiUbOmm8bP3d+AhZF0jPL+MAA7Z3i8LMq0Lso+5K1ZrWhTJYvoxttlJfigR8W8Mey7WAw=
  on:
    tags: true
    repo: mrtazz/simplenote.py
